name: linux-desktop-manager
version: '0.3'
summary: Remote manager for Linux desktops
description: |
  Linux Desktop Manager allows you to remotely manage your desktop.

  Note: This is not a RDP client.

grade: stable
confinement: devmode

apps:
  linux-desktop-manager:
    command: linux-desktop-manager
    #daemon: simple
    plugs:
      - network
  mid:
    command: cat /etc/machine-id

parts:
  linux-desktop-manager:
    plugin: python
    source: .
    requirements: requirements.txt
    build-packages:
      - pkg-config
      - libdbus-1-dev
      - libdbus-glib-1-dev
