name: linux-desktop-manager
version: '0.3'
summary: Remote manager for Linux desktops
description: |
  Linux Desktop Manager allows you to remotely manage your linux desktop.

grade: devel
confinement: strict

apps:
  linux-desktop-manager:
    command: linux-desktop-manager
    plugs:
      - network
      - desktop
  pair:
    environment:
      PYTHONIOENCODING: UTF-8
    command: qr_gen.sh

parts:
  linux-desktop-manager:
    plugin: python
    source: .
    requirements: requirements.txt
    build-packages:
      - pkg-config
      - libdbus-1-dev
      - libdbus-glib-1-dev

  pairing-launcher:
    plugin: dump
    source: .
    prime:
      - qr_gen.sh
